version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./src/mysql.chabin.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
    restart: always
    env_file: .env

  wordpress:
    build: ./
    depends_on:
      - db
    ports:
      - '8888:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: .env
    volumes:
      - ./src/app:/var/www/html/wp-content/themes/chabin

volumes:
  db_data: {}
